version: "3.8"

services:
  backend:
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:3000
      - ASPNETCORE_HTTP_PORTS=3000
      - ASPNETCORE_HTTPS_PORTS=3001
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=ConcentrationDataDb;Username=postgres;Password=postgres
    build:
      context: ./WebApiServer
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
    depends_on:
      - db
    command:
      [
        "sh",
        "-c",
        "dotnet ef database update && dotnet WebApiServer.dll --urls http://0.0.0.0:3000",
      ]

  frontend:
    build:
      context: ./ConProfileClient
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ConcentrationDataDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
